export type FaceDir = 'up' | 'down' | 'left' | 'right';

export const FOUR_FACES_DEFAULT_GLOBAL = {
  title: 'Four Faces',
  accentColor: '#C8102E',
  showDots: true,
  showArrows: true,
  showCloseButton: true,
  swipeThreshold: 40,
  closeButtonBg: 'rgba(0,0,0,0.5)',
  closeButtonColor: '#ffffff',
  brandName: '',
  brandColor: '#C8102E',
  logoSrc: '',
  logoAssetId: '',
  heroSrc: '',
  heroAssetId: '',
} as const;

export const FOUR_FACES_DEFAULT_HOME = {
  title: 'Headline principal',
  titleColor: '#1a1a1a',
  subtitle: 'Short description or product value proposition.',
  subtitleColor: '#555555',
  hintText: 'Swipe to explore',
  hintColor: '#999999',
  ctaLabel: 'Learn more',
  ctaUrl: '',
  ctaBg: '#C8102E',
  ctaTextColor: '#ffffff',
  bg: '#F2F2F2',
} as const;

export const FOUR_FACES_FACE_LABELS: Record<FaceDir, string> = {
  up: 'Up',
  down: 'Down',
  left: 'Left',
  right: 'Right',
};

export const FOUR_FACES_FACE_DEFAULTS: Record<FaceDir, {
  title: string;
  titleColor: string;
  body: string;
  bodyColor: string;
  ctaLabel: string;
  ctaUrl: string;
  imageSrc: string;
  imageAssetId: string;
  headerBg: string;
  copyBg: string;
  ctaBg: string;
  ctaTextColor: string;
}> = {
  up: {
    title: 'Title',
    titleColor: '#1a1a1a',
    body: 'Description of benefit or product feature.',
    bodyColor: '#555555',
    ctaLabel: 'Buy now',
    ctaUrl: '',
    imageSrc: '',
    imageAssetId: '',
    headerBg: '#C8102E',
    copyBg: '#FFFFFF',
    ctaBg: '#C8102E',
    ctaTextColor: '#ffffff',
  },
  down: {
    title: 'Title',
    titleColor: '#ffffff',
    body: 'Offer or promotional copy.',
    bodyColor: 'rgba(255,255,255,0.75)',
    ctaLabel: 'View offer',
    ctaUrl: '',
    imageSrc: '',
    imageAssetId: '',
    headerBg: '#F5C400',
    copyBg: '#1A1A1A',
    ctaBg: '#F5C400',
    ctaTextColor: '#1a1a1a',
  },
  left: {
    title: 'Title',
    titleColor: '#1a1a1a',
    body: 'Variety, flavors, or product range copy.',
    bodyColor: '#555555',
    ctaLabel: 'Explore',
    ctaUrl: '',
    imageSrc: '',
    imageAssetId: '',
    headerBg: '#FFFFFF',
    copyBg: '#FFFFFF',
    ctaBg: '#C8102E',
    ctaTextColor: '#ffffff',
  },
  right: {
    title: 'Title',
    titleColor: '#1a1a1a',
    body: 'Lifestyle or consumption moment copy.',
    bodyColor: '#555555',
    ctaLabel: 'Discover',
    ctaUrl: '',
    imageSrc: '',
    imageAssetId: '',
    headerBg: '#1A1A1A',
    copyBg: '#FFFFFF',
    ctaBg: '#C8102E',
    ctaTextColor: '#ffffff',
  },
};

export const FOUR_FACES_DEFAULT_PROPS = {
  ...FOUR_FACES_DEFAULT_GLOBAL,
  homeTitle: FOUR_FACES_DEFAULT_HOME.title,
  homeTitleColor: FOUR_FACES_DEFAULT_HOME.titleColor,
  homeSubtitle: FOUR_FACES_DEFAULT_HOME.subtitle,
  homeSubtitleColor: FOUR_FACES_DEFAULT_HOME.subtitleColor,
  homeHintText: FOUR_FACES_DEFAULT_HOME.hintText,
  homeHintColor: FOUR_FACES_DEFAULT_HOME.hintColor,
  homeCtaLabel: FOUR_FACES_DEFAULT_HOME.ctaLabel,
  homeCtaUrl: FOUR_FACES_DEFAULT_HOME.ctaUrl,
  homeCtaBg: FOUR_FACES_DEFAULT_HOME.ctaBg,
  homeCtaTextColor: FOUR_FACES_DEFAULT_HOME.ctaTextColor,
  homeBg: FOUR_FACES_DEFAULT_HOME.bg,
  upTitle: FOUR_FACES_FACE_DEFAULTS.up.title,
  upTitleColor: FOUR_FACES_FACE_DEFAULTS.up.titleColor,
  upBody: FOUR_FACES_FACE_DEFAULTS.up.body,
  upBodyColor: FOUR_FACES_FACE_DEFAULTS.up.bodyColor,
  upCtaLabel: FOUR_FACES_FACE_DEFAULTS.up.ctaLabel,
  upCtaUrl: FOUR_FACES_FACE_DEFAULTS.up.ctaUrl,
  upImageSrc: FOUR_FACES_FACE_DEFAULTS.up.imageSrc,
  upImageAssetId: FOUR_FACES_FACE_DEFAULTS.up.imageAssetId,
  upHeaderBg: FOUR_FACES_FACE_DEFAULTS.up.headerBg,
  upCopyBg: FOUR_FACES_FACE_DEFAULTS.up.copyBg,
  upCtaBg: FOUR_FACES_FACE_DEFAULTS.up.ctaBg,
  upCtaTextColor: FOUR_FACES_FACE_DEFAULTS.up.ctaTextColor,
  downTitle: FOUR_FACES_FACE_DEFAULTS.down.title,
  downTitleColor: FOUR_FACES_FACE_DEFAULTS.down.titleColor,
  downBody: FOUR_FACES_FACE_DEFAULTS.down.body,
  downBodyColor: FOUR_FACES_FACE_DEFAULTS.down.bodyColor,
  downCtaLabel: FOUR_FACES_FACE_DEFAULTS.down.ctaLabel,
  downCtaUrl: FOUR_FACES_FACE_DEFAULTS.down.ctaUrl,
  downImageSrc: FOUR_FACES_FACE_DEFAULTS.down.imageSrc,
  downImageAssetId: FOUR_FACES_FACE_DEFAULTS.down.imageAssetId,
  downHeaderBg: FOUR_FACES_FACE_DEFAULTS.down.headerBg,
  downCopyBg: FOUR_FACES_FACE_DEFAULTS.down.copyBg,
  downCtaBg: FOUR_FACES_FACE_DEFAULTS.down.ctaBg,
  downCtaTextColor: FOUR_FACES_FACE_DEFAULTS.down.ctaTextColor,
  leftTitle: FOUR_FACES_FACE_DEFAULTS.left.title,
  leftTitleColor: FOUR_FACES_FACE_DEFAULTS.left.titleColor,
  leftBody: FOUR_FACES_FACE_DEFAULTS.left.body,
  leftBodyColor: FOUR_FACES_FACE_DEFAULTS.left.bodyColor,
  leftCtaLabel: FOUR_FACES_FACE_DEFAULTS.left.ctaLabel,
  leftCtaUrl: FOUR_FACES_FACE_DEFAULTS.left.ctaUrl,
  leftImageSrc: FOUR_FACES_FACE_DEFAULTS.left.imageSrc,
  leftImageAssetId: FOUR_FACES_FACE_DEFAULTS.left.imageAssetId,
  leftHeaderBg: FOUR_FACES_FACE_DEFAULTS.left.headerBg,
  leftCopyBg: FOUR_FACES_FACE_DEFAULTS.left.copyBg,
  leftCtaBg: FOUR_FACES_FACE_DEFAULTS.left.ctaBg,
  leftCtaTextColor: FOUR_FACES_FACE_DEFAULTS.left.ctaTextColor,
  rightTitle: FOUR_FACES_FACE_DEFAULTS.right.title,
  rightTitleColor: FOUR_FACES_FACE_DEFAULTS.right.titleColor,
  rightBody: FOUR_FACES_FACE_DEFAULTS.right.body,
  rightBodyColor: FOUR_FACES_FACE_DEFAULTS.right.bodyColor,
  rightCtaLabel: FOUR_FACES_FACE_DEFAULTS.right.ctaLabel,
  rightCtaUrl: FOUR_FACES_FACE_DEFAULTS.right.ctaUrl,
  rightImageSrc: FOUR_FACES_FACE_DEFAULTS.right.imageSrc,
  rightImageAssetId: FOUR_FACES_FACE_DEFAULTS.right.imageAssetId,
  rightHeaderBg: FOUR_FACES_FACE_DEFAULTS.right.headerBg,
  rightCopyBg: FOUR_FACES_FACE_DEFAULTS.right.copyBg,
  rightCtaBg: FOUR_FACES_FACE_DEFAULTS.right.ctaBg,
  rightCtaTextColor: FOUR_FACES_FACE_DEFAULTS.right.ctaTextColor,
} as const;
