export const META_CAROUSEL_DEFAULT_SPONSORED_LABEL = 'Sponsored';
export const META_CAROUSEL_DEFAULT_PRIMARY_TEXT = 'Check out our latest products.';
export const META_CAROUSEL_DEFAULT_CTA_LABEL = 'Shop Now';

export const META_CAROUSEL_DEFAULT_PROPS = {
  brandName: 'Brand Name',
  brandAvatarSrc: '',
  brandAvatarAssetId: '',
  sponsoredLabel: META_CAROUSEL_DEFAULT_SPONSORED_LABEL,
  primaryText: META_CAROUSEL_DEFAULT_PRIMARY_TEXT,
  ctaLabel: META_CAROUSEL_DEFAULT_CTA_LABEL,
  ctaUrl: '',
  cardWidthPct: 75,
  imageHeightPct: 60,
  cardGap: 10,
  cardRadius: 8,
  slideCount: 3,
  slide1Src: '',
  slide1AssetId: '',
  slide1Kind: 'image',
  slide1Title: 'Product 1',
  slide1Description: '',
  slide2Src: '',
  slide2AssetId: '',
  slide2Kind: 'image',
  slide2Title: 'Product 2',
  slide2Description: '',
  slide3Src: '',
  slide3AssetId: '',
  slide3Kind: 'image',
  slide3Title: 'Product 3',
  slide3Description: '',
  slide4Src: '',
  slide4AssetId: '',
  slide4Kind: 'image',
  slide4Title: 'Product 4',
  slide4Description: '',
  slide5Src: '',
  slide5AssetId: '',
  slide5Kind: 'image',
  slide5Title: 'Product 5',
  slide5Description: '',
} as const;
