import { createElement } from 'react';
import { createModuleDefinition } from '../module-definition-factory';
import { renderFourFacesStage } from '../four-faces.renderer';
import { FourFacesInspector } from '../four-faces.inspector';

export const FourFacesDefinition = createModuleDefinition({
  type: 'four-faces',
  label: 'Four Faces',
  category: 'interactive',
  frame: { x: 40, y: 40, width: 320, height: 480, rotation: 0 },
  props: {
    title: 'Four Faces',
    accentColor: '#C8102E',
    showDots: true,
    showArrows: true,
    showCloseButton: true,
    swipeThreshold: 40,
    closeButtonBg: 'rgba(0,0,0,0.5)',
    closeButtonColor: '#ffffff',
    brandName: '',
    brandColor: '#C8102E',
    logoSrc: '',
    logoAssetId: '',
    homeTitle: 'Headline principal',
    homeTitleColor: '#1a1a1a',
    homeSubtitle: 'Short description or product value proposition.',
    homeSubtitleColor: '#555555',
    homeHintText: 'Swipe to explore',
    homeHintColor: '#999999',
    homeCtaLabel: 'Learn more',
    homeCtaUrl: '',
    homeCtaBg: '#C8102E',
    homeCtaTextColor: '#ffffff',
    heroSrc: '',
    heroAssetId: '',
    homeBg: '#F2F2F2',
    upTitle: 'Title',
    upTitleColor: '#1a1a1a',
    upBody: 'Description of benefit or product feature.',
    upBodyColor: '#555555',
    upCtaLabel: 'Buy now',
    upCtaUrl: '',
    upImageSrc: '',
    upImageAssetId: '',
    upHeaderBg: '#C8102E',
    upCopyBg: '#FFFFFF',
    upCtaBg: '#C8102E',
    upCtaTextColor: '#ffffff',
    downTitle: 'Title',
    downTitleColor: '#ffffff',
    downBody: 'Offer or promotional copy.',
    downBodyColor: 'rgba(255,255,255,0.75)',
    downCtaLabel: 'View offer',
    downCtaUrl: '',
    downImageSrc: '',
    downImageAssetId: '',
    downHeaderBg: '#F5C400',
    downCopyBg: '#1A1A1A',
    downCtaBg: '#F5C400',
    downCtaTextColor: '#1a1a1a',
    leftTitle: 'Title',
    leftTitleColor: '#1a1a1a',
    leftBody: 'Variety, flavors, or product range copy.',
    leftBodyColor: '#555555',
    leftCtaLabel: 'Explore',
    leftCtaUrl: '',
    leftImageSrc: '',
    leftImageAssetId: '',
    leftHeaderBg: '#FFFFFF',
    leftCopyBg: '#FFFFFF',
    leftCtaBg: '#C8102E',
    leftCtaTextColor: '#ffffff',
    rightTitle: 'Title',
    rightTitleColor: '#1a1a1a',
    rightBody: 'Lifestyle or consumption moment copy.',
    rightBodyColor: '#555555',
    rightCtaLabel: 'Discover',
    rightCtaUrl: '',
    rightImageSrc: '',
    rightImageAssetId: '',
    rightHeaderBg: '#1A1A1A',
    rightCopyBg: '#FFFFFF',
    rightCtaBg: '#C8102E',
    rightCtaTextColor: '#ffffff',
  },
  style: {
    backgroundColor: '#F2F2F2',
    color: '#1a1a1a',
    borderRadius: 0,
    opacity: 1,
  },
  renderStage: renderFourFacesStage,
  renderInspector: (node) => createElement(FourFacesInspector, { node }),
  exportDetail: 'Full-page interactive 4-face swipe ad',
  buildPortableExport: (node) => ({
    props: {
      exportRole: 'four-faces',
      accentColor: String(node.props.accentColor ?? ''),
      home: JSON.stringify({
        brandName: node.props.brandName,
        logoSrc: node.props.logoSrc,
        title: node.props.homeTitle,
        subtitle: node.props.homeSubtitle,
        hintText: node.props.homeHintText,
        ctaLabel: node.props.homeCtaLabel,
        ctaUrl: node.props.homeCtaUrl,
        heroSrc: node.props.heroSrc,
        homeBg: node.props.homeBg,
      }),
      faces: JSON.stringify([
        { dir: 'up', title: node.props.upTitle, body: node.props.upBody, src: node.props.upImageSrc, ctaLabel: node.props.upCtaLabel, ctaUrl: node.props.upCtaUrl },
        { dir: 'down', title: node.props.downTitle, body: node.props.downBody, src: node.props.downImageSrc, ctaLabel: node.props.downCtaLabel, ctaUrl: node.props.downCtaUrl },
        { dir: 'left', title: node.props.leftTitle, body: node.props.leftBody, src: node.props.leftImageSrc, ctaLabel: node.props.leftCtaLabel, ctaUrl: node.props.leftCtaUrl },
        { dir: 'right', title: node.props.rightTitle, body: node.props.rightBody, src: node.props.rightImageSrc, ctaLabel: node.props.rightCtaLabel, ctaUrl: node.props.rightCtaUrl },
      ]),
    },
  }),
});
