import { createElement } from 'react';
import { createModuleDefinition } from '../module-definition-factory';
import { renderTikTokVideoStage } from '../tiktok-video.renderer';
import { TikTokVideoInspector } from '../tiktok-video.inspector';

export const TikTokVideoDefinition = createModuleDefinition({
  type: 'tiktok-video',
  label: 'TikTok Video',
  category: 'media',
  frame: { x: 40, y: 40, width: 300, height: 600, rotation: 0 },
  props: {
    title: 'TikTok Video',
    videoSrc: '',
    videoAssetId: '',
    username: 'yourbrand',
    showVerified: true,
    avatarSrc: '',
    avatarAssetId: '',
    caption: 'Your ad copy goes here. Two lines visible.',
    hashtags: '#trending #fyp',
    likesCount: '12.4K',
    commentsCount: '842',
    sharesCount: '1.2K',
    ctaLabel: 'Shop Now',
    ctaUrl: '',
    ctaColor: '#fe2c55',
    ctaTextColor: '#ffffff',
    showHearts: true,
    showProgressBar: true,
    showMuteButton: true,
  },
  style: {
    backgroundColor: '#000000',
    color: '#ffffff',
    borderRadius: 0,
    opacity: 1,
  },
  renderStage: renderTikTokVideoStage,
  renderInspector: (node) => createElement(TikTokVideoInspector, { node }),
  exportDetail: 'TikTok-style video ad 300×600',
  buildPortableExport: (node) => ({
    props: {
      exportRole: 'tiktok-video',
      videoSrc: String(node.props.videoSrc ?? ''),
      videoAssetId: String(node.props.videoAssetId ?? ''),
      avatarSrc: String(node.props.avatarSrc ?? ''),
      avatarAssetId: String(node.props.avatarAssetId ?? ''),
      username: String(node.props.username ?? ''),
      showVerified: Boolean(node.props.showVerified ?? true),
      caption: String(node.props.caption ?? ''),
      hashtags: String(node.props.hashtags ?? ''),
      likesCount: String(node.props.likesCount ?? ''),
      commentsCount: String(node.props.commentsCount ?? ''),
      sharesCount: String(node.props.sharesCount ?? ''),
      ctaLabel: String(node.props.ctaLabel ?? ''),
      ctaUrl: String(node.props.ctaUrl ?? ''),
      ctaColor: String(node.props.ctaColor ?? '#fe2c55'),
      ctaTextColor: String(node.props.ctaTextColor ?? '#ffffff'),
      showHearts: Boolean(node.props.showHearts ?? true),
      showProgressBar: Boolean(node.props.showProgressBar ?? true),
      showMuteButton: Boolean(node.props.showMuteButton ?? true),
    },
  }),
});
