import { createElement } from 'react';
import { createModuleDefinition } from '../module-definition-factory';
import { renderVerticalAccordionStage } from '../vertical-accordion.renderer';
import { VerticalAccordionInspector } from '../vertical-accordion.inspector';

export const VerticalAccordionDefinition = createModuleDefinition({
  type: 'vertical-accordion',
  label: 'Vertical Accordion',
  category: 'interactive',
  frame: { x: 40, y: 40, width: 320, height: 480, rotation: 0 },
  props: {
    title: 'Vertical Accordion',
    showTopbar: true,
    brandLine1: 'BRAND NAME',
    brandLine2: 'Tagline',
    logoSrc: '',
    logoAssetId: '',
    row1Title: 'Section One',
    row1Chip: '',
    row1Src: '',
    row1AssetId: '',
    row1Bg: '#004B93',
    row1TextColor: '#ffffff',
    row2Title: 'Section Two',
    row2Chip: '',
    row2Src: '',
    row2AssetId: '',
    row2Bg: '#ffffff',
    row2TextColor: '#1a1a2e',
    row3Title: 'Section Three',
    row3Chip: '',
    row3Src: '',
    row3AssetId: '',
    row3Bg: '#1a1a2e',
    row3TextColor: '#ffffff',
    showEndcard: true,
    endcardLine1: 'BRAND',
    endcardLine2: '',
    endcardBg: '#004B93',
    endcardTextColor: '#ffffff',
    ctaText: 'Explore All >',
    ctaUrl: '',
    ctaBg: '#EE1C24',
    ctaTextColor: '#ffffff',
    autoplay: true,
    autoplayIntervalMs: 1000,
    showDots: true,
    stripHeight: 56,
    expandedHeight: 280,
  },
  style: {
    backgroundColor: '#0a0a0a',
    color: '#ffffff',
    borderRadius: 0,
    opacity: 1,
  },
  renderStage: renderVerticalAccordionStage,
  renderInspector: (node) => createElement(VerticalAccordionInspector, { node }),
  exportDetail: 'Vertical accordion with 3 expandable image rows',
  buildPortableExport: (node) => ({
    props: {
      exportRole: 'vertical-accordion',
      rows: JSON.stringify([
        { title: node.props.row1Title, src: node.props.row1Src, bg: node.props.row1Bg },
        { title: node.props.row2Title, src: node.props.row2Src, bg: node.props.row2Bg },
        { title: node.props.row3Title, src: node.props.row3Src, bg: node.props.row3Bg },
      ]),
      ctaText: String(node.props.ctaText ?? ''),
      ctaUrl: String(node.props.ctaUrl ?? ''),
    },
  }),
});
