import type { LucideIcon, LucideProps } from 'lucide-react';
import {
  ArrowDownToLine,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpToLine,
  ArrowUp,
  Boxes,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  Eye,
  EyeOff,
  Copy,
  CornerDownRight,
  Folder,
  GripVertical,
  Info,
  Images,
  Library,
  Layers3,
  Lock,
  LockOpen,
  Maximize2,
  Minus,
  MoreHorizontal,
  PanelBottomOpen,
  PanelLeftOpen,
  PanelRightOpen,
  Pause,
  Play,
  Plus,
  Ruler,
  ScanSearch,
  Settings2,
  SkipBack,
  Tags,
  Tag,
  Trash2,
  Upload,
  Workflow,
  X,
} from 'lucide-react';

type StudioIconProps = Omit<LucideProps, 'ref'> & {
  icon: LucideIcon;
};

export function StudioIcon({ icon: Icon, size = 16, strokeWidth = 1.9, className, ...props }: StudioIconProps): JSX.Element {
  return <Icon aria-hidden="true" size={size} strokeWidth={strokeWidth} className={`studio-icon${className ? ` ${className}` : ''}`} {...props} />;
}

export const StudioIcons = {
  arrowDownToLine: ArrowDownToLine,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpToLine: ArrowUpToLine,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  boxes: Boxes,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronsUpDown: ChevronsUpDown,
  circle: Circle,
  eye: Eye,
  eyeOff: EyeOff,
  copy: Copy,
  cornerDownRight: CornerDownRight,
  folder: Folder,
  gripVertical: GripVertical,
  info: Info,
  images: Images,
  library: Library,
  layers: Layers3,
  lock: Lock,
  lockOpen: LockOpen,
  maximize: Maximize2,
  minus: Minus,
  moreHorizontal: MoreHorizontal,
  panelBottomOpen: PanelBottomOpen,
  panelLeftOpen: PanelLeftOpen,
  panelRightOpen: PanelRightOpen,
  pause: Pause,
  play: Play,
  plus: Plus,
  ruler: Ruler,
  scanSearch: ScanSearch,
  settings: Settings2,
  skipBack: SkipBack,
  tags: Tags,
  tag: Tag,
  trash: Trash2,
  upload: Upload,
  workflow: Workflow,
  x: X,
} as const;
