import { createElement } from 'react';
import { createModuleDefinition } from '../module-definition-factory';
import { renderInteractiveVideoStage } from '../interactive-video.renderer';
import { InteractiveVideoInspector } from '../interactive-video.inspector';

export const InteractiveVideoDefinition = createModuleDefinition({
  type: 'interactive-video',
  label: 'Interactive Video',
  category: 'media',
  frame: { x: 40, y: 40, width: 320, height: 568, rotation: 0 },
  props: {
    title: 'Interactive Video',
    src: '',
    assetId: '',
    overlaysConfig: [],
    mimeType: 'video/mp4',
    vastTagUrl: '',
    vastMaxRedirects: 5,
    vastTimeoutMs: 8000,
    vastSkipOffsetOverride: '',
    vastCompanionZoneId: '',
    showCompanionSlot: true,
    showCompanionPlaceholder: true,
    companionLeftPct: 66,
    companionTopPct: 8,
    companionWidthPct: 28,
    companionHeightPct: 20,
    showVastDebug: true,
    showAnalyticsDebug: true,
    analyticsEventLimit: 8,
    posterSrc: '',
    posterAssetId: '',
    aspectRatio: '9/16',
    ariaLabel: 'Interactive video',
    autoPlay: true,
    startMuted: true,
    loop: false,
    showControls: false,
    clickToToggle: true,
    showMuteButton: true,
    showCountdownOverlay: false,
    countdownFromSeconds: 3,
    countdownTriggerMs: 0,
    countdownDurationMs: 3000,
    countdownCompletedLabel: 'Go',
    countdownLeftPct: 42,
    countdownTopPct: 12,
    countdownWidthPct: 16,
    countdownTextColor: '#ffffff',
    countdownBg: 'rgba(0,0,0,0.35)',
    countdownRadius: 999,
    countdownPaddingX: 14,
    countdownPaddingY: 10,
    showCtaOverlay: false,
    ctaLabel: 'Learn more',
    ctaUrl: '',
    ctaOpenInNewTab: true,
    ctaTriggerMs: 1500,
    ctaDurationMs: 4000,
    ctaLeftPct: 33,
    ctaTopPct: 78,
    ctaWidthPct: 34,
    ctaBg: '#ffffff',
    ctaTextColor: '#111111',
    ctaRadius: 999,
    ctaPaddingX: 18,
    ctaPaddingY: 10,
    ctaFontWeight: 700,
    showLogoOverlay: false,
    logoAssetId: '',
    logoAltText: '',
    logoTriggerMs: 0,
    logoDurationMs: 0,
    logoLeftPct: 5,
    logoTopPct: 5,
    logoWidthPct: 18,
    logoOpacity: 1,
    showCustomHtmlOverlay: false,
    customHtml: '<p>Custom content</p>',
    customHtmlTriggerMs: 0,
    customHtmlDurationMs: 0,
    customHtmlLeftPct: 10,
    customHtmlTopPct: 10,
    customHtmlWidthPct: 80,
    customHtmlHeightPct: 40,
    skipCountingLabel: 'Skip in {seconds}',
    skipLabel: 'Skip Ad ›',
    skipPosition: 'bottom-right',
  },
  style: {
    backgroundColor: '#080b16',
    color: '#ffffff',
    borderRadius: 18,
    opacity: 1,
  },
  renderStage: renderInteractiveVideoStage,
  renderInspector: (node) => createElement(InteractiveVideoInspector, { node }),
  exportDetail: 'Interactive video with configurable overlays and timeline actions',
  buildPortableExport: (node) => ({
    props: {
      exportRole: 'interactive-video',
      src: String(node.props.src ?? ''),
      assetId: String(node.props.assetId ?? ''),
      overlaysConfig: Array.isArray(node.props.overlaysConfig) ? node.props.overlaysConfig : [],
      mimeType: String(node.props.mimeType ?? ''),
      vastTagUrl: String(node.props.vastTagUrl ?? ''),
      vastMaxRedirects: Number(node.props.vastMaxRedirects ?? 5),
      vastTimeoutMs: Number(node.props.vastTimeoutMs ?? 8000),
      vastSkipOffsetOverride: String(node.props.vastSkipOffsetOverride ?? ''),
      vastCompanionZoneId: String(node.props.vastCompanionZoneId ?? ''),
      showCompanionSlot: Boolean(node.props.showCompanionSlot ?? true),
      showCompanionPlaceholder: Boolean(node.props.showCompanionPlaceholder ?? true),
      companionLeftPct: Number(node.props.companionLeftPct ?? 66),
      companionTopPct: Number(node.props.companionTopPct ?? 8),
      companionWidthPct: Number(node.props.companionWidthPct ?? 28),
      companionHeightPct: Number(node.props.companionHeightPct ?? 20),
      showVastDebug: Boolean(node.props.showVastDebug ?? true),
      showAnalyticsDebug: Boolean(node.props.showAnalyticsDebug ?? true),
      analyticsEventLimit: Number(node.props.analyticsEventLimit ?? 8),
      posterSrc: String(node.props.posterSrc ?? ''),
      posterAssetId: String(node.props.posterAssetId ?? ''),
      aspectRatio: String(node.props.aspectRatio ?? '9/16'),
      ariaLabel: String(node.props.ariaLabel ?? ''),
      autoPlay: Boolean(node.props.autoPlay ?? true),
      startMuted: Boolean(node.props.startMuted ?? true),
      loop: Boolean(node.props.loop ?? false),
      showControls: Boolean(node.props.showControls ?? false),
      clickToToggle: Boolean(node.props.clickToToggle ?? true),
      showMuteButton: Boolean(node.props.showMuteButton ?? true),
      showCountdownOverlay: Boolean(node.props.showCountdownOverlay ?? false),
      countdownFromSeconds: Number(node.props.countdownFromSeconds ?? 3),
      countdownTriggerMs: Number(node.props.countdownTriggerMs ?? 0),
      countdownDurationMs: Number(node.props.countdownDurationMs ?? 3000),
      countdownCompletedLabel: String(node.props.countdownCompletedLabel ?? 'Go'),
      countdownLeftPct: Number(node.props.countdownLeftPct ?? 42),
      countdownTopPct: Number(node.props.countdownTopPct ?? 12),
      countdownWidthPct: Number(node.props.countdownWidthPct ?? 16),
      countdownTextColor: String(node.props.countdownTextColor ?? '#ffffff'),
      countdownBg: String(node.props.countdownBg ?? 'rgba(0,0,0,0.35)'),
      showCtaOverlay: Boolean(node.props.showCtaOverlay ?? false),
      ctaLabel: String(node.props.ctaLabel ?? 'Learn more'),
      ctaUrl: String(node.props.ctaUrl ?? ''),
      ctaOpenInNewTab: Boolean(node.props.ctaOpenInNewTab ?? true),
      ctaTriggerMs: Number(node.props.ctaTriggerMs ?? 1500),
      ctaDurationMs: Number(node.props.ctaDurationMs ?? 4000),
      ctaLeftPct: Number(node.props.ctaLeftPct ?? 33),
      ctaTopPct: Number(node.props.ctaTopPct ?? 78),
      ctaWidthPct: Number(node.props.ctaWidthPct ?? 34),
      ctaBg: String(node.props.ctaBg ?? '#ffffff'),
      ctaTextColor: String(node.props.ctaTextColor ?? '#111111'),
      showLogoOverlay: Boolean(node.props.showLogoOverlay ?? false),
      logoAssetId: String(node.props.logoAssetId ?? ''),
      logoAltText: String(node.props.logoAltText ?? ''),
      logoTriggerMs: Number(node.props.logoTriggerMs ?? 0),
      logoDurationMs: Number(node.props.logoDurationMs ?? 0),
      logoLeftPct: Number(node.props.logoLeftPct ?? 5),
      logoTopPct: Number(node.props.logoTopPct ?? 5),
      logoWidthPct: Number(node.props.logoWidthPct ?? 18),
      logoOpacity: Number(node.props.logoOpacity ?? 1),
      showCustomHtmlOverlay: Boolean(node.props.showCustomHtmlOverlay ?? false),
      customHtml: String(node.props.customHtml ?? ''),
      customHtmlTriggerMs: Number(node.props.customHtmlTriggerMs ?? 0),
      customHtmlDurationMs: Number(node.props.customHtmlDurationMs ?? 0),
      customHtmlLeftPct: Number(node.props.customHtmlLeftPct ?? 10),
      customHtmlTopPct: Number(node.props.customHtmlTopPct ?? 10),
      customHtmlWidthPct: Number(node.props.customHtmlWidthPct ?? 80),
      customHtmlHeightPct: Number(node.props.customHtmlHeightPct ?? 40),
      skipCountingLabel: String(node.props.skipCountingLabel ?? 'Skip in {seconds}'),
      skipLabel: String(node.props.skipLabel ?? 'Skip Ad ›'),
      skipPosition: String(node.props.skipPosition ?? 'bottom-right'),
    },
  }),
});
