import { execFile } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);
const outputPath = resolve(process.cwd(), 'src/export/runtime-bundle.generated.ts');
const outputDir = dirname(outputPath);
const generatedRuntimePath = resolve(process.cwd(), 'src/export/__generated__/runtime.iife.js');

await execFileAsync(
  process.execPath,
  [
    resolve(process.cwd(), '../../node_modules/vite/dist/node/cli.js'),
    'build',
    '--config',
    'vite.runtime.config.ts',
  ],
  { cwd: process.cwd() },
);

const runtimeBundle = await readFile(generatedRuntimePath, 'utf8');
const escapedBundle = JSON.stringify(runtimeBundle);
const bundleSource = `// AUTO-GENERATED by scripts/build-runtime.mjs — DO NOT EDIT
/* eslint-disable */
export const SMX_RUNTIME_BUNDLE = ${escapedBundle};
`;

await mkdir(outputDir, { recursive: true });
await writeFile(outputPath, bundleSource, 'utf8');

process.stdout.write(`generated ${outputPath}\n`);
