export const INTERACTIVE_VIDEO_DEFAULT_CTA_LABEL = 'Learn more';
export const INTERACTIVE_VIDEO_DEFAULT_COUNTDOWN_COMPLETED_LABEL = 'Go';
export const INTERACTIVE_VIDEO_DEFAULT_SKIP_COUNTING_LABEL = 'Skip in {seconds}';
export const INTERACTIVE_VIDEO_DEFAULT_SKIP_LABEL = 'Skip Ad';
